# Generated by Django 5.2.1 on 2025-05-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="subidos/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
