# Generated by Django 5.2.1 on 2025-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0003_alter_archivo_archivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]