# Generated by Django 5.2.1 on 2025-07-09 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0005_avataruser_backgrounduser_comment_filesmessage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
        migrations.AlterField(
            model_name="avataruser",
            name="file_path",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="backgrounduser",
            name="file_path",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="filesmessage",
            name="file_path",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="filespost",
            name="file_path",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_date", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_vibe.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
