# Generated by Django 5.2.1 on 2025-07-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0006_remove_post_title_alter_avataruser_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesmessage",
            name="temp_file",
            field=models.FileField(blank=True, null=True, upload_to="temp/"),
        ),
        migrations.AddField(
            model_name="filespost",
            name="temp_file",
            field=models.FileField(blank=True, null=True, upload_to="temp/"),
        ),
        migrations.AddField(
            model_name="user",
            name="auth_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
