# Generated by Django 5.2.1 on 2025-07-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0008_alter_filesmessage_file_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filespost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos",
                to="app_vibe.post",
            ),
        ),
    ]
