# Generated by Django 5.2.1 on 2025-07-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0009_alter_filespost_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filespost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_vibe.post"
            ),
        ),
    ]
