# Generated by Django 5.2.1 on 2025-05-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0002_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivo",
            name="archivo",
            field=models.FileField(upload_to="archivos/"),
        ),
    ]
