# Generated by Django 5.2.1 on 2025-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0007_filesmessage_temp_file_filespost_temp_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesmessage",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filesmessage",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="filespost",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filespost",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
