# Generated by Django 5.2.1 on 2025-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0010_alter_filespost_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                ],
                default="sent",
                max_length=50,
            ),
        ),
    ]
