# Generated by Django 5.2.1 on 2025-07-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0011_alter_message_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="upload_menssage",
            new_name="upload_message",
        ),
    ]
