# Generated by Django 5.2.1 on 2025-08-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0012_rename_create_at_message_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesmessage",
            name="temp_file",
        ),
        migrations.RemoveField(
            model_name="filespost",
            name="temp_file",
        ),
    ]
