# Generated by Django 5.2.1 on 2025-09-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_vibe", "0013_remove_filesmessage_temp_file_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BackgroundUser",
            new_name="BannerUser",
        ),
    ]
